server:
  port: 9600

spring:
  data:
    solr:
      host: http://baseCentos:8080/solr  # 单机版solr配置

  # mysql 相关配置
  datasource:
    url: jdbc:mysql://baseCentos:3306/online?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

# fastdfs配置
fdfs:
  so-timeout: 1500 # 读取时间
  connect-timeout: 600  # 链接超时时间
  pool: # 连接池
    jmx-enabled: false
  thumb-image:  # 缩略图
    width: 100
    height: 100
  tracker-list: baseCentos:22122   # 跟踪器地址


